### ISSUE TITLE
DB discrepancy

### ISSUE THREAD

**Issue by Martii** [F9y4ng/GreasyFork-Scripts#20]
https://openuserjs.org/users/f9y4ng and https://openuserjs.org/users/t3xtf0rm4tgmail.com point to this repository.

So when you update a script here it apparently gets updated to OUJS twice. One account needs to be severed, merged *(which will require an additional step from you)*, or deleted *(which will require an additional step from you)*. Since there is very little to confirm who is who please let me know as soon as possible which account you wish to keep as your main one, otherwise we'll be severing the accounts in about 24 hours. This wasn't your fault way back when there was a security issue that was introduced by another contributor so I am giving you a chance to pick what to do.

Thank you for your attention on this matter.

OUJS Admin

**Comment by F9y4ng** [comment]
Hi, @Martii Those two accounts you mentioned are all belong to me.

1. Three months ago, I planned to change OAuth/OpenID from Google to GitHub to achieve namespace consistency. However, after I changed my account, I found that switching verification accounts was just a new one, but not a replacement, so two OUJS accounts appeared, one is t3xtf0rm4tgmail.com and the other is f9y4ng.

2. I have tried to delete the original script to use the new script, but I found that OUJS didn't have a GreasyFork's script migration pointing function. Deleting the original script will make the users who have installed the script through the deleted source unable to update or automatically redirect to the new script address. Therefore, only two accounts could be updated at the same time.

3. Since the updates to both accounts use different script names, and there are thousands of installations in a few months. If only merge, or delete duplicate accounts or scripts, it will cause users who have already installed the deleted script to be unable to update, or cause the script to be installed repeatedly because each script source has a different script name.

So, it's best to keep two accounts, because merge or delete accounts will cause very complex operations and unnecessary, but both accounts are my own. If you think delete or merge is necessary or mandatory in your site, Please inform me in advance.

Thank you for your reminder.

**Comment by Martii** [comment]
You may still keep both accounts but they can't both point to your account here on GH. The google account is the natural candidate from removal of the linkage. You will however have to manually update the google accounts scripts because the webhook wasn't intended to do this with non-GH accounts and can cause some unintended consequences down the line.

**Comment by Martii** [comment]
Also typically you would change the `@downloadURL` to signify migration to another account but that is clearly up to you.

OUJS Admin

**Comment by Martii** [comment]
So they are severed now since you want to keep both accounts.

**Comment by Martii** [comment]
One other quick note... you almost got your GH OUJS account removed *(not deleted but permanent removal)* from an invalid fork sweep positive... but I look into all instances as carefully as possible. So it's best to have something on the google OUJS account saying your new scripts are at your GH OUJS account whether it be a profile statement or the corresponding `@downloadURL`s. 

I'm not the only one who acts on moderation and if I'm not here hopefully they'll look at this issue before any action is taken place. More likely they'll check your profile and script source though. 

Apologies for many comments here but a lot to cover.

OUJS Admin

**Comment by F9y4ng** [comment]
Hi, @Martii 

I've been manually updating the script on OUJS in the past and haven't configured webhook, so your concern doesn't exist.

Since I haven't figured out the update policy for OUJS, I plan to temporarily suspend updating the script on OUJS. Make plans after all the problems have been solved.

Thank you for your patient explanation.

**Comment by Martii** [comment]
The DB discrepancy is resolved on our end [from up there](https://github.com/F9y4ng/GreasyFork-Scripts/issues/20#issuecomment-913116925)... your GH account was created in late 2018 btw... so the "Three months ago, I planned to change OAuth/OpenID from Google to GitHub to achieve namespace consistency. However, after I changed my account, I found that switching verification accounts was just a new one, but not a replacement, so two OUJS accounts appeared" doesn't quite fit the narrative but doesn't really matter.

Manually updating the script also includes importing functions but that was also fixed a while after the initial bug was fixed on our site... so well within your time frame of memberships... which is why I created this issue to clarify and give benefit of the doubt.

Like I said, if I'm not around to query and another actionable party doesn't dig deep enough you'll get flagged again with an invalid fork sweep. Hopefully everyone else will check your repo here for some buzz words but I can't guarantee that... so it's best to have you resolve what you feel is necessary. I would recommend, at minimum, a profile notice on your old account to the newer to avoid this. That's sufficient evidence to negate a positive find on a sweep.

If you choose to consolidate at some point it's best to do the edited [recommendation above](https://github.com/F9y4ng/GreasyFork-Scripts/issues/20#issuecomment-913116085).

Since your old account is one of those ones from google I would be willing to transfer your stats to the new account when you get your end resolved. Please feel free to ping me when you are ready if you so choose.

OUJS Admin
