### ISSUE TITLE
GreasyFork更新过于频繁

### ISSUE THREAD

**Issue by a76yyyy** [F9y4ng/GreasyFork-Scripts#4]
建议允许设置自动检测更新周期，或者修改greasyfork同步更新周期
个人建议，如果不合适请直接closed issue

**Comment by F9y4ng** [comment]
脚本中已设置更新频率的参数：默认四小时

  /* The following variable is used to define the expiration time of version detection.
   * In order to reduce the query pressure on the script source server as much as possible,
   * Please don`t set the Query-cache expiration time too short. So we set 4 hours by default,
   * And to reduce update-tips frequency, you can extend the expireTime to a few days, or even weeks.
   * (s = second, m = minute, h = hour, d = day, w = week) */

  const expireTime = "4h";

将该值设置为较长的时间，如3d（三天）或更长 2w（两周）即可降低更新频率。

**Comment by a76yyyy** [comment]
修改后每次更新是否会重置？

**Comment by F9y4ng** [comment]
> 修改后每次更新是否会重置？

先更新至最新版，以后的更新安装不会重置缓存时间。

**Comment by qrqhuang** [comment]
其实我并不需要这个自动检测的功能。 用greasyfork自带的我就够用了。 现在的更新提示太过于打扰用户。

**Comment by F9y4ng** [comment]
> 其实我并不需要这个自动检测的功能。 用greasyfork自带的我就够用了。 现在的更新提示太过于打扰用户。

代码中有关闭代码更新检测功能的参数：

```const isVersionDetection = true; // Set "false" to turn off the Version Detection forever.```

**Comment by qrqhuang** [comment]
> 
> 
> > 其实我并不需要这个自动检测的功能。 用greasyfork自带的我就够用了。 现在的更新提示太过于打扰用户。
> 
> 代码中有关闭代码更新检测功能的参数：
> 
> `const isVersionDetection = true; // Set "false" to turn off the Version Detection forever.`

可能我更愿意false是一个默认值。

**Comment by F9y4ng** [comment]
> > > 其实我并不需要这个自动检测的功能。 用greasyfork自带的我就够用了。 现在的更新提示太过于打扰用户。
> > 
> > 
> > 代码中有关闭代码更新检测功能的参数：
> > `const isVersionDetection = true; // Set "false" to turn off the Version Detection forever.`
> 
> 可能我更愿意false是一个默认值。

也有人愿意true是一个默认值。如果实在不能接受，请使用其他油猴脚本替代。

**Comment by qrqhuang** [comment]
好的 打扰了
